In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/resumes/training_data.csv")

In [3]:
df.head()

,Resume ID,Resume Text,Education,Experience Years,Skills,Job Role,Category
0,R000000,Education: Bachelor's in Computer Science Expe...,Bachelor's in Computer Science,2,Market Research|Maven|Java|REST API|Spring Boo...,Java Backend Developer,Technology
1,R000001,Education: Master's in Microbiology Experience...,Master's in Microbiology,3,Agile|Data Analysis|Precision|Problem Solving|...,Microbiologist,Science & Research
2,R000002,Education: Apprenticeship Experience: 2 years ...,Apprenticeship,2,React|Customer Service|Technical Knowledge|Plu...,Plumber,Skilled Trades
3,R000003,Education: Bachelor's in Computer Science Expe...,Bachelor's in Computer Science,0,MySQL|Query Optimization|Symfony|Terraform|PHP...,PHP Developer,Technology
4,R000004,Education: Bachelor's in Design Experience: 3 ...,Bachelor's in Design,3,Problem Solving|Docker|Creativity|Scrum|Ansibl...,Art Director,Creative & Design

In [4]:
df.shape

(10000, 7)

In [5]:
df.columns

Index(['Resume ID', 'Resume Text', 'Education', 'Experience Years', 'Skills',
       'Job Role', 'Category'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Resume ID         10000 non-null  str
 1   Resume Text       10000 non-null  str
 2   Education         10000 non-null  str
 3   Experience Years  10000 non-null  int64
 4   Skills            10000 non-null  str
 5   Job Role          10000 non-null  str
 6   Category          10000 non-null  str
dtypes: int64(1), str(6)
memory usage: 3.8 MB

In [7]:
df.describe(include="all")

,Resume ID,Resume Text,Education,Experience Years,Skills,Job Role,Category
count,10000,10000,10000,10000.000000,10000,10000,10000
unique,10000,10000,257,NaN,10000,324,42
top,R000000,Education: Bachelor's in Computer Science Expe...,Bachelor's in Computer Science,NaN,Market Research|Maven|Java|REST API|Spring Boo...,Java Backend Developer,Technology
freq,1,1,1425,NaN,1,50,2511
mean,NaN,NaN,NaN,3.133800,NaN,NaN,NaN
std,NaN,NaN,NaN,2.180269,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,3.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,4.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,13.000000,NaN,NaN,NaN

In [8]:
df.isnull().sum()

Resume ID           0
Resume Text         0
Education           0
Experience Years    0
Skills              0
Job Role            0
Category            0
dtype: int64

In [9]:
df["Job Role"].nunique()

324

In [10]:
df["Job Role"].value_counts().head(20)

Job Role
Java Backend Developer      50
Automotive Engineer         47
Electronics Engineer        44
School Principal            44
Announcer                   43
Hairstylist                 43
Cashier                     42
Audit Manager               42
Executive Assistant         41
HVAC Technician             41
Medical Technologist        41
Grant Writer                41
Microbiologist              40
Conservation Officer        40
Museum Curator              40
HR Manager                  40
Mobile Developer Android    40
Sports Manager              40
Aerospace Engineer          40
Network Engineer            39
Name: count, dtype: int64

In [11]:
df["Category"].value_counts()

Category
Technology                      2511
Data & Analytics                 568
Healthcare                       488
Marketing & Sales                463
Engineering & Manufacturing      435
Creative & Design                334
Skilled Trades                   279
Operations & Supply Chain        266
Human Resources                  263
Finance & Accounting             252
Legal Services                   245
Retail & Hospitality             225
Entertainment & Media            194
Hospitality & Food Service       184
Education & Training             183
Beauty & Wellness                170
Private Sector Management        161
Law Enforcement                  161
Construction & Real Estate       159
Transportation                   153
Agriculture & Food               147
Science & Research               140
Sports & Recreation              137
Consulting                       134
Administration                   132
Media & Entertainment            128
Transportation & Logistics       122
Sales & Customer Service         117
Agriculture                      116
Hospitality & Tourism            107
Arts & Culture                   101
Non-profit & Charity              99
Human Services & Social Work      98
Media Production                  98
Conservation                      97
Energy & Utilities                91
Government & Public Service       90
Research & Development            86
Sports & Athletics                75
Information Services              67
Veterinary                        65
Environmental                     59
Name: count, dtype: int64

In [12]:
df["Resume Text Length"] = df["Resume Text"].str.len()

df["Resume Text Length"].describe()

count    10000.000000
mean       168.549100
std         17.031113
min        105.000000
25%        156.000000
50%        168.000000
75%        180.000000
max        225.000000
Name: Resume Text Length, dtype: float64

In [13]:
df["Skill Count"] = df["Skills"].apply(
    lambda x: len(str(x).split("|"))
)

df["Skill Count"].describe()

count    10000.000000
mean         9.495300
std          1.108829
min          8.000000
25%          9.000000
50%          9.000000
75%         10.000000
max         11.000000
Name: Skill Count, dtype: float64

In [14]:
print(df["Resume Text"][0])
print(df["Resume Text"][10])
print(df["Resume Text"][100])

Education: Bachelor's in Computer Science Experience: 2 years Skills: Market Research, Maven, Java, REST API, Spring Boot, Microservices, Statistics, SQL
Education: Master's in Computer Science Experience: 6 years Skills: Statistics, Research, Deep Learning, Shell Scripting, Python, TensorFlow, PyTorch, Network Security
Education: Bachelor's in Cybersecurity Experience: 3 years Skills: Vulnerability Testing, Problem Solving, Security Tools, Reporting, Risk Assessment, Security Testing, Redis, Django

In [16]:
import os

print(os.getcwd())

C:\Users\Faizur Rahman\PycharmProjects\Resume-Matcher-NLP\notebooks

In [17]:
from pathlib import Path

Path.cwd()

WindowsPath('C:/Users/Faizur Rahman/PycharmProjects/Resume-Matcher-NLP/notebooks')

In [18]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Faizur Rahman\PycharmProjects\Resume-Matcher-NLP\data\raw\skills\skills_list.csv"
)

print(len(df))
print(df["Skill Name"].duplicated().sum())

120
5